# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import pdf_service_pb2 as pdf__service__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in pdf_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PDFServiceStub:
    """Service definition for PDF Processing Microservice
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.MergePDF = channel.unary_unary(
                '/pdfservice.PDFService/MergePDF',
                request_serializer=pdf__service__pb2.MergePDFRequest.SerializeToString,
                response_deserializer=pdf__service__pb2.MergePDFResponse.FromString,
                _registered_method=True)
        self.SplitPDF = channel.unary_unary(
                '/pdfservice.PDFService/SplitPDF',
                request_serializer=pdf__service__pb2.SplitPDFRequest.SerializeToString,
                response_deserializer=pdf__service__pb2.SplitPDFResponse.FromString,
                _registered_method=True)
        self.CheckStatus = channel.unary_unary(
                '/pdfservice.PDFService/CheckStatus',
                request_serializer=pdf__service__pb2.StatusRequest.SerializeToString,
                response_deserializer=pdf__service__pb2.StatusResponse.FromString,
                _registered_method=True)


class PDFServiceServicer:
    """Service definition for PDF Processing Microservice
    """

    def MergePDF(self, request, context):
        """RPC method to merge multiple PDF files
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SplitPDF(self, request, context):
        """RPC method to split PDF pages
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckStatus(self, request, context):
        """RPC method to check job status
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PDFServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'MergePDF': grpc.unary_unary_rpc_method_handler(
                    servicer.MergePDF,
                    request_deserializer=pdf__service__pb2.MergePDFRequest.FromString,
                    response_serializer=pdf__service__pb2.MergePDFResponse.SerializeToString,
            ),
            'SplitPDF': grpc.unary_unary_rpc_method_handler(
                    servicer.SplitPDF,
                    request_deserializer=pdf__service__pb2.SplitPDFRequest.FromString,
                    response_serializer=pdf__service__pb2.SplitPDFResponse.SerializeToString,
            ),
            'CheckStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckStatus,
                    request_deserializer=pdf__service__pb2.StatusRequest.FromString,
                    response_serializer=pdf__service__pb2.StatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pdfservice.PDFService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('pdfservice.PDFService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PDFService:
    """Service definition for PDF Processing Microservice
    """

    @staticmethod
    def MergePDF(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pdfservice.PDFService/MergePDF',
            pdf__service__pb2.MergePDFRequest.SerializeToString,
            pdf__service__pb2.MergePDFResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SplitPDF(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pdfservice.PDFService/SplitPDF',
            pdf__service__pb2.SplitPDFRequest.SerializeToString,
            pdf__service__pb2.SplitPDFResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pdfservice.PDFService/CheckStatus',
            pdf__service__pb2.StatusRequest.SerializeToString,
            pdf__service__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class MutexServiceStub:
    """Service for Experiment 4: Ricart-Agrawala distributed mutual exclusion.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RequestAccess = channel.unary_unary(
                '/pdfservice.MutexService/RequestAccess',
                request_serializer=pdf__service__pb2.AccessRequest.SerializeToString,
                response_deserializer=pdf__service__pb2.AccessReply.FromString,
                _registered_method=True)


class MutexServiceServicer:
    """Service for Experiment 4: Ricart-Agrawala distributed mutual exclusion.
    """

    def RequestAccess(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MutexServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RequestAccess': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestAccess,
                    request_deserializer=pdf__service__pb2.AccessRequest.FromString,
                    response_serializer=pdf__service__pb2.AccessReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pdfservice.MutexService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('pdfservice.MutexService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MutexService:
    """Service for Experiment 4: Ricart-Agrawala distributed mutual exclusion.
    """

    @staticmethod
    def RequestAccess(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pdfservice.MutexService/RequestAccess',
            pdf__service__pb2.AccessRequest.SerializeToString,
            pdf__service__pb2.AccessReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class LockServiceStub:
    """--- Experiment 5: Deadlock simulation & resolution ---
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AcquireLock = channel.unary_unary(
                '/pdfservice.LockService/AcquireLock',
                request_serializer=pdf__service__pb2.LockRequest.SerializeToString,
                response_deserializer=pdf__service__pb2.LockReply.FromString,
                _registered_method=True)
        self.ReleaseLock = channel.unary_unary(
                '/pdfservice.LockService/ReleaseLock',
                request_serializer=pdf__service__pb2.LockRequest.SerializeToString,
                response_deserializer=pdf__service__pb2.LockReply.FromString,
                _registered_method=True)


class LockServiceServicer:
    """--- Experiment 5: Deadlock simulation & resolution ---
    """

    def AcquireLock(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReleaseLock(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LockServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AcquireLock': grpc.unary_unary_rpc_method_handler(
                    servicer.AcquireLock,
                    request_deserializer=pdf__service__pb2.LockRequest.FromString,
                    response_serializer=pdf__service__pb2.LockReply.SerializeToString,
            ),
            'ReleaseLock': grpc.unary_unary_rpc_method_handler(
                    servicer.ReleaseLock,
                    request_deserializer=pdf__service__pb2.LockRequest.FromString,
                    response_serializer=pdf__service__pb2.LockReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pdfservice.LockService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('pdfservice.LockService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LockService:
    """--- Experiment 5: Deadlock simulation & resolution ---
    """

    @staticmethod
    def AcquireLock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pdfservice.LockService/AcquireLock',
            pdf__service__pb2.LockRequest.SerializeToString,
            pdf__service__pb2.LockReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReleaseLock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pdfservice.LockService/ReleaseLock',
            pdf__service__pb2.LockRequest.SerializeToString,
            pdf__service__pb2.LockReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
